### ISSUE TITLE
Bosch SHC isn't discovered

### ISSUE THREAD

**Issue by saxn-paule** [tschamm/boschshc-hass#34]
After installing the custom component via HACS (v0.4.12) and restarting HA the SHC isn't discovered and I'm not able to configure the integration.

`Failed to get public information from SHC controller: HTTPSConnectionPool(host='169.254.112.7', port=8446): Max retries exceeded with url: /smarthome/public/information (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f19b814a8b0>, 'Connection to 169.254.112.7 timed out. (connect timeout=30)'))`

With the official Bosch SHC integration it works without any problem.

**Comment by tschamm** [comment]
@saxn-paule This issue is related with link-local addresses reported by zeroconf. Obviously, the last patch did not fix this correctly and I have to dig deeper into this issue. You can try to configure the component not by using zeroconf, but instead by adding it via the menu (Settings -> Integrations -> Add Integration -> Bosch SHC) using the correct IP address of the SHC.

**Comment by saxn-paule** [comment]
Do I need to delete the official integration after I added the SHC?

**Comment by tschamm** [comment]
Yes, you have to delete the integration in the menu.

**Comment by saxn-paule** [comment]
Thank you. That seems to work. I will update this issue when I got some Bosch devices.

**Comment by saxn-paule** [comment]
Got a TRV that works without any issues.
The only drawback is, that it was found only after a reboot of Home-Assistant.

**Comment by tschamm** [comment]
Fixed discovery step by commit 1e5c48a24e36678a3e53f3644ad40d7bbf7c22a9.
